name = "snready"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# KV namespace for storing user access
[[kv_namespaces]]
binding = "SNREADY_ACCESS"
id = "bcb7c1925c84424cb90713533b286c63"

[vars]
SITE_URL = "https://snready.com"
