#!/usr/bin/env npx tsx
/**
 * Generates functions/lib/question-bank.generated.ts, a static import map of every
 * certification topic question file. Cloudflare Pages Functions are bundled with
 * esbuild, which needs static JSON imports, so the premium questions API
 * (functions/api/questions.ts) reads questions through this map instead of the
 * static site. Run: npx tsx scripts/generate-question-bank.ts [--check]
 *
 * --check exits non-zero when the committed file is out of date.
 */

import fs from "node:fs";
import path from "node:path";
import { getAllTopicSlugs } from "@/lib/data";

const OUTPUT_FILE = path.join(process.cwd(), "functions", "lib", "question-bank.generated.ts");

function identifier(...parts: string[]): string {
  return parts
    .join("_")
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr: string | undefined) => (chr ? chr.toUpperCase() : ""))
    .replace(/^[0-9]/, (digit) => `_${digit}`);
}

export function renderQuestionBank(): string {
  const topicSlugs = getAllTopicSlugs();
  const certSlugs = Array.from(new Set(topicSlugs.map(({ certification }) => certification)));

  const imports: string[] = [];
  const entries: string[] = [];

  for (const cert of certSlugs) {
    const topicsIdentifier = identifier(cert, "topics");
    imports.push(`import ${topicsIdentifier} from "../../data/topics/${cert}-topics.json";`);

    const topicEntries: string[] = [];
    for (const { topic } of topicSlugs.filter(({ certification }) => certification === cert)) {
      const questionFile = path.join(process.cwd(), "data", "questions", cert, `${topic}.json`);
      if (!fs.existsSync(questionFile)) continue;
      const questionsIdentifier = identifier(cert, topic, "questions");
      imports.push(`import ${questionsIdentifier} from "../../data/questions/${cert}/${topic}.json";`);
      topicEntries.push(`      ${JSON.stringify(topic)}: ${questionsIdentifier}.questions,`);
    }

    entries.push(
      [
        `  ${JSON.stringify(cert)}: {`,
        `    topics: ${topicsIdentifier}.topics,`,
        `    questions: {`,
        ...topicEntries,
        `    },`,
        `  },`,
      ].join("\n")
    );
  }

  return [
    "// AUTO-GENERATED by scripts/generate-question-bank.ts. Do not edit by hand.",
    "// Static import map of premium-capable question files for Cloudflare Pages Functions.",
    "",
    'import certificationsData from "../../data/certifications.json";',
    ...imports,
    "",
    "export interface QuestionBankTopic {",
    "  slug: string;",
    "  questionCount: number;",
    "}",
    "",
    "export interface QuestionBankCertification {",
    "  topics: QuestionBankTopic[];",
    "  questions: Record<string, unknown[]>;",
    "}",
    "",
    "export const QUESTION_BANK_CERTIFICATIONS: Array<{ slug: string; name: string; allQuestionsFree?: boolean }> =",
    "  certificationsData.certifications;",
    "",
    "export const QUESTION_BANK: Record<string, QuestionBankCertification> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function main() {
  const rendered = renderQuestionBank();
  const current = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, "utf8") : "";

  if (process.argv.includes("--check")) {
    if (current !== rendered) {
      console.error("functions/lib/question-bank.generated.ts is out of date. Run: npx tsx scripts/generate-question-bank.ts");
      process.exit(1);
    }
    console.log("Question bank import map is up to date.");
    return;
  }

  if (current !== rendered) {
    fs.writeFileSync(OUTPUT_FILE, rendered, "utf8");
    console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  } else {
    console.log("Question bank import map already up to date.");
  }
}

// Only run when executed directly (tests import renderQuestionBank).
if (process.argv[1] && path.basename(process.argv[1]).startsWith("generate-question-bank")) {
  main();
}
