// AUTO-GENERATED by scripts/generate-question-bank.ts. Do not edit by hand.
// Static import map of premium-capable question files for Cloudflare Pages Functions.

import certificationsData from "../../data/certifications.json";
import csaTopics from "../../data/topics/csa-topics.json";
import csaUiNavigationQuestions from "../../data/questions/csa/ui-navigation.json";
import csaInstanceConfigurationQuestions from "../../data/questions/csa/instance-configuration.json";
import csaListsFormsCollaborationQuestions from "../../data/questions/csa/lists-forms-collaboration.json";
import csaReportingDashboardsQuestions from "../../data/questions/csa/reporting-dashboards.json";
import csaSelfServiceAutomationQuestions from "../../data/questions/csa/self-service-automation.json";
import csaDatabaseAdministrationQuestions from "../../data/questions/csa/database-administration.json";
import csaUserAdministrationQuestions from "../../data/questions/csa/user-administration.json";
import csaDataMigrationIntegrationQuestions from "../../data/questions/csa/data-migration-integration.json";
import cisDfTopics from "../../data/topics/cis-df-topics.json";
import cisDfConfigurationQuestions from "../../data/questions/cis-df/configuration.json";
import cisDfIngestQuestions from "../../data/questions/cis-df/ingest.json";
import cisDfGovernQuestions from "../../data/questions/cis-df/govern.json";
import cisDfInsightQuestions from "../../data/questions/cis-df/insight.json";
import cisDfCsdmFundamentalsQuestions from "../../data/questions/cis-df/csdm-fundamentals.json";
import cadTopics from "../../data/topics/cad-topics.json";
import cadScriptingApisQuestions from "../../data/questions/cad/scripting-apis.json";
import cadBusinessRulesQuestions from "../../data/questions/cad/business-rules.json";
import cadClientScriptsQuestions from "../../data/questions/cad/client-scripts.json";
import cadUiPoliciesActionsQuestions from "../../data/questions/cad/ui-policies-actions.json";
import cadScriptIncludesQuestions from "../../data/questions/cad/script-includes.json";
import cadIntegrationRestQuestions from "../../data/questions/cad/integration-rest.json";
import cadApplicationDevelopmentQuestions from "../../data/questions/cad/application-development.json";
import cisItsmTopics from "../../data/topics/cis-itsm-topics.json";
import cisItsmIncidentManagementQuestions from "../../data/questions/cis-itsm/incident-management.json";
import cisItsmChangeManagementQuestions from "../../data/questions/cis-itsm/change-management.json";
import cisItsmProblemManagementQuestions from "../../data/questions/cis-itsm/problem-management.json";
import cisItsmRequestManagementQuestions from "../../data/questions/cis-itsm/request-management.json";
import cisItsmItsmOverviewQuestions from "../../data/questions/cis-itsm/itsm-overview.json";
import cisItsmSlaManagementQuestions from "../../data/questions/cis-itsm/sla-management.json";
import cisItsmReportingMetricsQuestions from "../../data/questions/cis-itsm/reporting-metrics.json";
import cisDiscoveryTopics from "../../data/topics/cis-discovery-topics.json";
import cisDiscoveryPatternDesignQuestions from "../../data/questions/cis-discovery/pattern-design.json";
import cisDiscoveryDiscoveryConfigurationQuestions from "../../data/questions/cis-discovery/discovery-configuration.json";
import cisDiscoveryCmdbIntegrationQuestions from "../../data/questions/cis-discovery/cmdb-integration.json";
import cisDiscoveryEngagementReadinessQuestions from "../../data/questions/cis-discovery/engagement-readiness.json";
import cisCsmTopics from "../../data/topics/cis-csm-topics.json";
import cisCsmFoundationalDataModelQuestions from "../../data/questions/cis-csm/foundational-data-model.json";
import cisCsmCsmConfigurationQuestions from "../../data/questions/cis-csm/csm-configuration.json";
import cisCsmCaseManagementQuestions from "../../data/questions/cis-csm/case-management.json";
import cisCsmWorkspacePortalsAnalyticsQuestions from "../../data/questions/cis-csm/workspace-portals-analytics.json";
import cisCsmBestPracticesKnowledgeQuestions from "../../data/questions/cis-csm/best-practices-knowledge.json";
import cisHamTopics from "../../data/topics/cis-ham-topics.json";
import cisHamItamFundamentalsQuestions from "../../data/questions/cis-ham/itam-fundamentals.json";
import cisHamDataIntegrityQuestions from "../../data/questions/cis-ham/data-integrity.json";
import cisHamPracticalManagementQuestions from "../../data/questions/cis-ham/practical-management.json";
import cisHamOperationalIntegrationQuestions from "../../data/questions/cis-ham/operational-integration.json";
import cisHamFinancialManagementQuestions from "../../data/questions/cis-ham/financial-management.json";
import cisVrTopics from "../../data/topics/cis-vr-topics.json";
import cisVrApplicationsQuestions from "../../data/questions/cis-vr/applications.json";
import cisVrDataIngestionQuestions from "../../data/questions/cis-vr/data-ingestion.json";
import cisVrManagementToolsQuestions from "../../data/questions/cis-vr/management-tools.json";
import cisVrAutomationQuestions from "../../data/questions/cis-vr/automation.json";
import cisVrReportingQuestions from "../../data/questions/cis-vr/reporting.json";
import cisSirTopics from "../../data/topics/cis-sir-topics.json";
import cisSirOverviewQuestions from "../../data/questions/cis-sir/overview.json";
import cisSirCreationQuestions from "../../data/questions/cis-sir/creation.json";
import cisSirIntegrationsQuestions from "../../data/questions/cis-sir/integrations.json";
import cisSirManagementQuestions from "../../data/questions/cis-sir/management.json";
import cisSirAutomationQuestions from "../../data/questions/cis-sir/automation.json";
import cisSirRiskQuestions from "../../data/questions/cis-sir/risk.json";
import cisSpTopics from "../../data/topics/cis-sp-topics.json";
import cisSpInitialDomainSetupQuestions from "../../data/questions/cis-sp/initial-domain-setup.json";
import cisSpDataSeparationQuestions from "../../data/questions/cis-sp/data-separation.json";
import cisSpFoundationalDataManagementQuestions from "../../data/questions/cis-sp/foundational-data-management.json";
import cisSpProcessSeparationQuestions from "../../data/questions/cis-sp/process-separation.json";
import cisSpDomainSupportApplicationsQuestions from "../../data/questions/cis-sp/domain-support-applications.json";
import cisSpmTopics from "../../data/topics/cis-spm-topics.json";
import cisSpmSpmImplementationOverviewQuestions from "../../data/questions/cis-spm/spm-implementation-overview.json";
import cisSpmIdeaAndDemandQuestions from "../../data/questions/cis-spm/idea-and-demand.json";
import cisSpmProjectManagementQuestions from "../../data/questions/cis-spm/project-management.json";
import cisSpmResourceManagementQuestions from "../../data/questions/cis-spm/resource-management.json";
import cisSpmTimecardManagementQuestions from "../../data/questions/cis-spm/timecard-management.json";
import cisSpmSpmFinancialsQuestions from "../../data/questions/cis-spm/spm-financials.json";
import cisSpmPortfolioPlanningWorkspaceQuestions from "../../data/questions/cis-spm/portfolio-planning-workspace.json";
import cisSpmSpmPlatformAnalyticsDashboardsQuestions from "../../data/questions/cis-spm/spm-platform-analytics-dashboards.json";
import cisSpmSpmBetterTogetherQuestions from "../../data/questions/cis-spm/spm-better-together.json";
import cisTprmTopics from "../../data/topics/cis-tprm-topics.json";
import cisTprmFundamentalsQuestions from "../../data/questions/cis-tprm/fundamentals.json";
import cisTprmCoreConfigurationQuestions from "../../data/questions/cis-tprm/core-configuration.json";
import cisTprmAssessmentConfigurationQuestions from "../../data/questions/cis-tprm/assessment-configuration.json";
import cisTprmThirdPartyPortalQuestions from "../../data/questions/cis-tprm/third-party-portal.json";
import cisTprmSupportingProcessesQuestions from "../../data/questions/cis-tprm/supporting-processes.json";
import cisTprmApplicationRelationshipsQuestions from "../../data/questions/cis-tprm/application-relationships.json";
import cpoaTopics from "../../data/topics/cpoa-topics.json";
import cpoaStrategyQuestions from "../../data/questions/cpoa/strategy.json";
import cpoaPeopleQuestions from "../../data/questions/cpoa/people.json";
import cpoaProcessQuestions from "../../data/questions/cpoa/process.json";
import cpoaTechnologyQuestions from "../../data/questions/cpoa/technology.json";
import cpoaDataQuestions from "../../data/questions/cpoa/data.json";
import cpoaGovernanceQuestions from "../../data/questions/cpoa/governance.json";
import cisHrTopics from "../../data/topics/cis-hr-topics.json";
import cisHrHrSystemArchitectureQuestions from "../../data/questions/cis-hr/hr-system-architecture.json";
import cisHrCoreHrApplicationsQuestions from "../../data/questions/cis-hr/core-hr-applications.json";
import cisHrHrJourneysQuestions from "../../data/questions/cis-hr/hr-journeys.json";
import cisHrHrSecurityQuestions from "../../data/questions/cis-hr/hr-security.json";
import cisRcTopics from "../../data/topics/cis-rc-topics.json";
import cisRcGrcOverviewQuestions from "../../data/questions/cis-rc/grc-overview.json";
import cisRcImplementationPlanningQuestions from "../../data/questions/cis-rc/implementation-planning.json";
import cisRcEntityFrameworkQuestions from "../../data/questions/cis-rc/entity-framework.json";
import cisRcPolicyComplianceQuestions from "../../data/questions/cis-rc/policy-compliance.json";
import cisRcRiskAdvancedRiskQuestions from "../../data/questions/cis-rc/risk-advanced-risk.json";
import cisRcCommonElementsQuestions from "../../data/questions/cis-rc/common-elements.json";
import cisRcAuditAdvancedAuditQuestions from "../../data/questions/cis-rc/audit-advanced-audit.json";
import cisSamTopics from "../../data/topics/cis-sam-topics.json";
import cisSamSamFundamentalsQuestions from "../../data/questions/cis-sam/sam-fundamentals.json";
import cisSamDataIntegrityQuestions from "../../data/questions/cis-sam/data-integrity.json";
import cisSamSoftwareComplianceQuestions from "../../data/questions/cis-sam/software-compliance.json";
import cisSamOperationalIntegrationQuestions from "../../data/questions/cis-sam/operational-integration.json";
import cisSamExtendingSamQuestions from "../../data/questions/cis-sam/extending-sam.json";
import cisEmTopics from "../../data/topics/cis-em-topics.json";
import cisEmEmOverviewQuestions from "../../data/questions/cis-em/em-overview.json";
import cisEmArchitectureDiscoveryQuestions from "../../data/questions/cis-em/architecture-discovery.json";
import cisEmEventConfigurationQuestions from "../../data/questions/cis-em/event-configuration.json";
import cisEmAlertsTasksQuestions from "../../data/questions/cis-em/alerts-tasks.json";
import cisEmEventSourcesQuestions from "../../data/questions/cis-em/event-sources.json";
import cisEmMetricIntelligenceQuestions from "../../data/questions/cis-em/metric-intelligence.json";
import cisFsmTopics from "../../data/topics/cis-fsm-topics.json";
import cisFsmFundamentalsQuestions from "../../data/questions/cis-fsm/fundamentals.json";
import cisFsmPlanningQuestions from "../../data/questions/cis-fsm/planning.json";
import cisFsmProcessesQuestions from "../../data/questions/cis-fsm/processes.json";
import cisFsmRelatedQuestions from "../../data/questions/cis-fsm/related.json";
import cisPaTopics from "../../data/topics/cis-pa-topics.json";
import cisPaArchitectureDeploymentQuestions from "../../data/questions/cis-pa/architecture-deployment.json";
import cisPaIndicatorsQuestions from "../../data/questions/cis-pa/indicators.json";
import cisPaBreakdownsQuestions from "../../data/questions/cis-pa/breakdowns.json";
import cisPaDataCollectionQuestions from "../../data/questions/cis-pa/data-collection.json";
import cisPaVisualizationDashboardsQuestions from "../../data/questions/cis-pa/visualization-dashboards.json";
import cisPaAdminAdvancedQuestions from "../../data/questions/cis-pa/admin-advanced.json";
import cisSmTopics from "../../data/topics/cis-sm-topics.json";
import cisSmPatternDesignQuestions from "../../data/questions/cis-sm/pattern-design.json";
import cisSmSmConfigurationQuestions from "../../data/questions/cis-sm/sm-configuration.json";
import cisSmDiscoveryConfigurationQuestions from "../../data/questions/cis-sm/discovery-configuration.json";
import cisSmMachineLearningQuestions from "../../data/questions/cis-sm/machine-learning.json";
import cisSmCmdbIntegrationQuestions from "../../data/questions/cis-sm/cmdb-integration.json";
import cisSmEngagementReadinessQuestions from "../../data/questions/cis-sm/engagement-readiness.json";

export interface QuestionBankTopic {
  slug: string;
  questionCount: number;
}

export interface QuestionBankCertification {
  topics: QuestionBankTopic[];
  questions: Record<string, unknown[]>;
}

export const QUESTION_BANK_CERTIFICATIONS: Array<{ slug: string; name: string; allQuestionsFree?: boolean }> =
  certificationsData.certifications;

export const QUESTION_BANK: Record<string, QuestionBankCertification> = {
  "csa": {
    topics: csaTopics.topics,
    questions: {
      "ui-navigation": csaUiNavigationQuestions.questions,
      "instance-configuration": csaInstanceConfigurationQuestions.questions,
      "lists-forms-collaboration": csaListsFormsCollaborationQuestions.questions,
      "reporting-dashboards": csaReportingDashboardsQuestions.questions,
      "self-service-automation": csaSelfServiceAutomationQuestions.questions,
      "database-administration": csaDatabaseAdministrationQuestions.questions,
      "user-administration": csaUserAdministrationQuestions.questions,
      "data-migration-integration": csaDataMigrationIntegrationQuestions.questions,
    },
  },
  "cis-df": {
    topics: cisDfTopics.topics,
    questions: {
      "configuration": cisDfConfigurationQuestions.questions,
      "ingest": cisDfIngestQuestions.questions,
      "govern": cisDfGovernQuestions.questions,
      "insight": cisDfInsightQuestions.questions,
      "csdm-fundamentals": cisDfCsdmFundamentalsQuestions.questions,
    },
  },
  "cad": {
    topics: cadTopics.topics,
    questions: {
      "scripting-apis": cadScriptingApisQuestions.questions,
      "business-rules": cadBusinessRulesQuestions.questions,
      "client-scripts": cadClientScriptsQuestions.questions,
      "ui-policies-actions": cadUiPoliciesActionsQuestions.questions,
      "script-includes": cadScriptIncludesQuestions.questions,
      "integration-rest": cadIntegrationRestQuestions.questions,
      "application-development": cadApplicationDevelopmentQuestions.questions,
    },
  },
  "cis-itsm": {
    topics: cisItsmTopics.topics,
    questions: {
      "incident-management": cisItsmIncidentManagementQuestions.questions,
      "change-management": cisItsmChangeManagementQuestions.questions,
      "problem-management": cisItsmProblemManagementQuestions.questions,
      "request-management": cisItsmRequestManagementQuestions.questions,
      "itsm-overview": cisItsmItsmOverviewQuestions.questions,
      "sla-management": cisItsmSlaManagementQuestions.questions,
      "reporting-metrics": cisItsmReportingMetricsQuestions.questions,
    },
  },
  "cis-discovery": {
    topics: cisDiscoveryTopics.topics,
    questions: {
      "pattern-design": cisDiscoveryPatternDesignQuestions.questions,
      "discovery-configuration": cisDiscoveryDiscoveryConfigurationQuestions.questions,
      "cmdb-integration": cisDiscoveryCmdbIntegrationQuestions.questions,
      "engagement-readiness": cisDiscoveryEngagementReadinessQuestions.questions,
    },
  },
  "cis-csm": {
    topics: cisCsmTopics.topics,
    questions: {
      "foundational-data-model": cisCsmFoundationalDataModelQuestions.questions,
      "csm-configuration": cisCsmCsmConfigurationQuestions.questions,
      "case-management": cisCsmCaseManagementQuestions.questions,
      "workspace-portals-analytics": cisCsmWorkspacePortalsAnalyticsQuestions.questions,
      "best-practices-knowledge": cisCsmBestPracticesKnowledgeQuestions.questions,
    },
  },
  "cis-ham": {
    topics: cisHamTopics.topics,
    questions: {
      "itam-fundamentals": cisHamItamFundamentalsQuestions.questions,
      "data-integrity": cisHamDataIntegrityQuestions.questions,
      "practical-management": cisHamPracticalManagementQuestions.questions,
      "operational-integration": cisHamOperationalIntegrationQuestions.questions,
      "financial-management": cisHamFinancialManagementQuestions.questions,
    },
  },
  "cis-vr": {
    topics: cisVrTopics.topics,
    questions: {
      "applications": cisVrApplicationsQuestions.questions,
      "data-ingestion": cisVrDataIngestionQuestions.questions,
      "management-tools": cisVrManagementToolsQuestions.questions,
      "automation": cisVrAutomationQuestions.questions,
      "reporting": cisVrReportingQuestions.questions,
    },
  },
  "cis-sir": {
    topics: cisSirTopics.topics,
    questions: {
      "overview": cisSirOverviewQuestions.questions,
      "creation": cisSirCreationQuestions.questions,
      "integrations": cisSirIntegrationsQuestions.questions,
      "management": cisSirManagementQuestions.questions,
      "automation": cisSirAutomationQuestions.questions,
      "risk": cisSirRiskQuestions.questions,
    },
  },
  "cis-sp": {
    topics: cisSpTopics.topics,
    questions: {
      "initial-domain-setup": cisSpInitialDomainSetupQuestions.questions,
      "data-separation": cisSpDataSeparationQuestions.questions,
      "foundational-data-management": cisSpFoundationalDataManagementQuestions.questions,
      "process-separation": cisSpProcessSeparationQuestions.questions,
      "domain-support-applications": cisSpDomainSupportApplicationsQuestions.questions,
    },
  },
  "cis-spm": {
    topics: cisSpmTopics.topics,
    questions: {
      "spm-implementation-overview": cisSpmSpmImplementationOverviewQuestions.questions,
      "idea-and-demand": cisSpmIdeaAndDemandQuestions.questions,
      "project-management": cisSpmProjectManagementQuestions.questions,
      "resource-management": cisSpmResourceManagementQuestions.questions,
      "timecard-management": cisSpmTimecardManagementQuestions.questions,
      "spm-financials": cisSpmSpmFinancialsQuestions.questions,
      "portfolio-planning-workspace": cisSpmPortfolioPlanningWorkspaceQuestions.questions,
      "spm-platform-analytics-dashboards": cisSpmSpmPlatformAnalyticsDashboardsQuestions.questions,
      "spm-better-together": cisSpmSpmBetterTogetherQuestions.questions,
    },
  },
  "cis-tprm": {
    topics: cisTprmTopics.topics,
    questions: {
      "fundamentals": cisTprmFundamentalsQuestions.questions,
      "core-configuration": cisTprmCoreConfigurationQuestions.questions,
      "assessment-configuration": cisTprmAssessmentConfigurationQuestions.questions,
      "third-party-portal": cisTprmThirdPartyPortalQuestions.questions,
      "supporting-processes": cisTprmSupportingProcessesQuestions.questions,
      "application-relationships": cisTprmApplicationRelationshipsQuestions.questions,
    },
  },
  "cpoa": {
    topics: cpoaTopics.topics,
    questions: {
      "strategy": cpoaStrategyQuestions.questions,
      "people": cpoaPeopleQuestions.questions,
      "process": cpoaProcessQuestions.questions,
      "technology": cpoaTechnologyQuestions.questions,
      "data": cpoaDataQuestions.questions,
      "governance": cpoaGovernanceQuestions.questions,
    },
  },
  "cis-hr": {
    topics: cisHrTopics.topics,
    questions: {
      "hr-system-architecture": cisHrHrSystemArchitectureQuestions.questions,
      "core-hr-applications": cisHrCoreHrApplicationsQuestions.questions,
      "hr-journeys": cisHrHrJourneysQuestions.questions,
      "hr-security": cisHrHrSecurityQuestions.questions,
    },
  },
  "cis-rc": {
    topics: cisRcTopics.topics,
    questions: {
      "grc-overview": cisRcGrcOverviewQuestions.questions,
      "implementation-planning": cisRcImplementationPlanningQuestions.questions,
      "entity-framework": cisRcEntityFrameworkQuestions.questions,
      "policy-compliance": cisRcPolicyComplianceQuestions.questions,
      "risk-advanced-risk": cisRcRiskAdvancedRiskQuestions.questions,
      "common-elements": cisRcCommonElementsQuestions.questions,
      "audit-advanced-audit": cisRcAuditAdvancedAuditQuestions.questions,
    },
  },
  "cis-sam": {
    topics: cisSamTopics.topics,
    questions: {
      "sam-fundamentals": cisSamSamFundamentalsQuestions.questions,
      "data-integrity": cisSamDataIntegrityQuestions.questions,
      "software-compliance": cisSamSoftwareComplianceQuestions.questions,
      "operational-integration": cisSamOperationalIntegrationQuestions.questions,
      "extending-sam": cisSamExtendingSamQuestions.questions,
    },
  },
  "cis-em": {
    topics: cisEmTopics.topics,
    questions: {
      "em-overview": cisEmEmOverviewQuestions.questions,
      "architecture-discovery": cisEmArchitectureDiscoveryQuestions.questions,
      "event-configuration": cisEmEventConfigurationQuestions.questions,
      "alerts-tasks": cisEmAlertsTasksQuestions.questions,
      "event-sources": cisEmEventSourcesQuestions.questions,
      "metric-intelligence": cisEmMetricIntelligenceQuestions.questions,
    },
  },
  "cis-fsm": {
    topics: cisFsmTopics.topics,
    questions: {
      "fundamentals": cisFsmFundamentalsQuestions.questions,
      "planning": cisFsmPlanningQuestions.questions,
      "processes": cisFsmProcessesQuestions.questions,
      "related": cisFsmRelatedQuestions.questions,
    },
  },
  "cis-pa": {
    topics: cisPaTopics.topics,
    questions: {
      "architecture-deployment": cisPaArchitectureDeploymentQuestions.questions,
      "indicators": cisPaIndicatorsQuestions.questions,
      "breakdowns": cisPaBreakdownsQuestions.questions,
      "data-collection": cisPaDataCollectionQuestions.questions,
      "visualization-dashboards": cisPaVisualizationDashboardsQuestions.questions,
      "admin-advanced": cisPaAdminAdvancedQuestions.questions,
    },
  },
  "cis-sm": {
    topics: cisSmTopics.topics,
    questions: {
      "pattern-design": cisSmPatternDesignQuestions.questions,
      "sm-configuration": cisSmSmConfigurationQuestions.questions,
      "discovery-configuration": cisSmDiscoveryConfigurationQuestions.questions,
      "machine-learning": cisSmMachineLearningQuestions.questions,
      "cmdb-integration": cisSmCmdbIntegrationQuestions.questions,
      "engagement-readiness": cisSmEngagementReadinessQuestions.questions,
    },
  },
};
